// availableLines.js
const availableLines = {
  place1_B2F: {
    placename: "법학관 B2",
    buildingname: "법학관",
    previousplace: null,
    afterplace: "법학관 B1",
    placeinfo: "이마트, 커피빈",
    time: "운동장까지 30초",
    leftColor: "7F3E98",
    rightColor: "7F3E98",
  },
  place1_B1F: {
    placename: "법학관 B1",
    buildingname: "법학관",
    previousplace: "법학관 B2",
    afterplace: "법학관 1F",
    placeinfo: "프린트",
    time: null,
    leftColor: "7F3E98",
    rightColor: "7F3E98",
  },
  place1_1F: {
    placename: "법학관 1F",
    buildingname: "법학관",
    previousplace: "법학관 B1",
    afterplace: "법학관 2F",
    placeinfo: null,
    time: null,
    leftColor: "7F3E98",
    rightColor: "7F3E98",
  },
  place1_3F: {
    placename: "법학관 3F",
    buildingname: "법학관",
    previousplace: "법학관 2F",
    afterplace: "법학관 4F",
    placeinfo: null,
    time: null,
    leftColor: "7F3E98",
    rightColor: "7F3E98",
  },
  place1_4F: {
    placename: "법학관 4F",
    buildingname: "법학관",
    previousplace: "법학관 3F",
    afterplace: "법학관 5F",
    placeinfo: null,
    time: null,
    leftColor: "7F3E98",
    rightColor: "7F3E98",
  },
  place1_5F: {
    placename: "법학관 5F",
    buildingname: "법학관",
    previousplace: "법학관 4F",
    afterplace: "법학관 옥상",
    placeinfo: null,
    time: null,
    leftColor: "7F3E98",
    rightColor: "7F3E98",
  },
  place1_6F: {
    placename: "법학관 옥상",
    buildingname: "법학관",
    previousplace: "법학관 5F",
    afterplace: null,
    placeinfo: null,
    time: "종로02 정류장: 1분 30초",
    leftColor: "7F3E98",
    rightColor: "7F3E98",
  },
  connect1: "법학관2F-수선관3F",
  connect2: "수선관1F-수선관별관1F",
  connect3: "수선관8F-수선관별관8F",
  connect4: "수선관5F-수선관별관5F",
  connect5: "퇴계2F-다산2F-경영4F",
  connect6: "퇴계3F-다산3F",
  connect7: "퇴계4F-다산4F",
  connect8: "퇴계5F-다산5F",
  connect9: "다산1F-경영3F",
  connect10: "6주B2-국제1F",
};

export default availableLines;
